version: '3'

services:
  zy-player-web:
    image: zy-player-web:latest
    container_name: zy-player-web
    ports:
      - "80:80"
    volumes:
      - ./deploy/locations.conf:/etc/nginx/locations.conf
    restart: always
